version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step1/step3/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링부트를 종료합니다.
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새버전의 스프링부트를 시작합니다.
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: health.sh # 새 스프링부트가 정상적으로 실행됐는지 확인합니다.
      timeout: 60
      runas: ec2-user

# permissions
# CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다
# hooks
# CodeDeploy 배포 단계에서 실행할 명령어를 지정합니다.
# ApplicationStart라는 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 합니다.
# timeout 60으로 스크립트 실행 60초 이상 수행되면 실패가 됩니다.
